# Generated by Django 5.2.5 on 2025-08-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('CARDIO', 'Cardio'), ('STRENGTH', 'Strength'), ('FLEXIBILITY', 'Flexibility'), ('OTHER', 'Other')], default='STRENGTH', max_length=50)),
                ('muscle_group', models.CharField(choices=[('CHEST', 'Chest'), ('SHOULDERS', 'Shoulders'), ('BACK', 'Back'), ('ARMS', 'Arms'), ('LEGS', 'Legs'), ('CORE', 'Core'), ('OTHER', 'Other')], default='CHEST', max_length=33)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
